example_data = {'doc_id': 'confecom_srl',
 'pages': {'0': {'text_body_coords': [[237, 348],
    [1178, 332],
    [260, 1686],
    [1201, 1671]],
   'lectura': 'O DE SOCIEDAD DE RESPONSABILIDAD LIMITADA. “CONFECOM S.\n\n12)\n\n \n\nROA, argentina, casada en primeras nupcias con Raul Alberto LESCA-\n\nNO, nacida el 10 de marzo de 1966, comerciante, titular del docu-\nmento nacional de identidad número 17.636.488, C.U.I.T.: 27-\n17636488-8, y Yamila Belén LESCANO, argentina, soltera, nacida el\n6 de marzo de 1998, comerciante, titular del documento nácional de\nidentidad número 41.048.026, C.U.I.L.: 27-41048026-9, ambos domici-\nliados en Pico 4785, Ciudad Autónoma de Buenos Aires; resuelven de-\njar constituida una sociedad de responsabilidad limitada que se re-\n\ngirá por la Ley número 19.550/22.903 y el siguiente estatuto:\n\nPRIMERA: La sociedad se denomina: "CONFECOM S.R.L."” y tiene su do-\nmicilio legal en jurisdicción de la Ciudad Autónoma de Buenos Ai-\nres, pudiendo establecer agencias o sucursales en cualquier lugar\n\ndel país o del extranjero.-\n\nSEGUNDA: Su duración es de 99 años contados a partir de la inscrip-\n\nción en el Registro Público de Comercio. -\n\nTERCERA: La sociedad tiene por objeto realizar por cuenta propia o\nde terceros, en forma independiente o asociadas a terceros, dentro\no fuera de la República Argentina a las siguientes actividades:\nCompraventa, importación, exportación, comercialización, represen-\ntación, fabricación, refacción, composición, confección, depósi-\nto, transporte, despacho e industrialización de todo tipo de ropa,\nindumentaria, calzado y sus derivados, botonería, mercería, artícu-\nlos textiles, materias primas, productos y subproductos destinados\na la industria del vestido, y demás prendas y accesorios inheren-\ntes al ramo. Para el cumplimiento del objeto social, la sociedad\ntendrá plena capacidad jurídica para adquirir derechos y contraer\nobligaciones y ejercer actos que no sean prohibidos por las leyes\n\no este estatuto.-\n\nCUARTA: El capital social se fija en la suma de pesos CINCUENTA\nmil ($50.000) dividido en 5.000 cuotas de valor nominal $ 10 cada'},
  '1': {'text_body_coords': [[106, 302],
    [1040, 307],
    [98, 1651],
    [1032, 1656]],
   'lectura': 'en un 23 por ciento y el resto se integrará dentro de los plazos\n\nlegales.-\n\nQUINTA: La administración y representación legal estará a cargo de\nuno o más gerentes, socios o no, en forma individual e indistinta,\npor el plazo de duración de la sociedad. En tal carácter tienen to-\ndas las facultades para realizar los actos y contratos tendientes\nal cumplimiento del objeto de la sociedad, inclusive los previstos\nen los artículos 375, del Código Civil y Comercial, y 9 del Decre-\nto ley 5.965/63.- Los gerentes garantizarán su gestión mediante la\nconstitución de una garantía del tipo, modalidades y de los montos\nno inferiores a los establecidos en las resoluciones vigentes de\nla autoridad administrativa de control y las que se dicten con pos-\n\nterioridad.-\n\nSEXTA: Las resoluciones sociales se adoptarán en la forma dispues-\nta en los arts. 159, primera parte párrafo segundo de la ley\n19550.- Rigen las mayorías previstas en el art. 160 de la ley 19.\n550.- y cada cuota da derecho a un voto. Toda comunicación o cita-\nción a los socios se sujetará a lo dispuesto en el art. 159 último\n\npárrafo de la ley citada.-\n\nSEPTIMA: Las cuotas son transmisibles rigiendo las disposiciones\ndel art. 153 de la ley 19.550, dejando constancia que para la ven-\nta a extraños a la sociedad se requerirá la conformidad de la mayo-\nría del capital, estableciendo a favor de los restantes socios un\nderecho de preferencia en la compra de las cuotas sociales que se\nvendan.-\n\nOCTAVA: El ejercicio social cierra el 31 de Marzo de cada año, a\ncuya fecha se realizara el balance general que se pondrá a disposi-\nción de los socios con no menos de 15 días de anticipación a su\nconsideración.-\n\nNOVENA: De las utilidades liquidas y realizadas se destinarán: a)\nEl 5% al fondo de reserva legal, hasta alcanzar el 20% del capital\nsocial.- b)El importe que se establezca para retribución de los ge-\nrentes y Cc) El remanente previa deducción de cualquier otra reser-\nva que los socios dispusieran constituir, se distribuirá entre los\nmismos en proporción al capital integrado.-\n\nDECIMA: Disuelta la sociedad por cualquiera de ¡as causales previs-\ntas en el artículo 94 de la ley 19.550.-, la liquidación será prac-'},
  '2': {'text_body_coords': [[631, 318],
    [1171, 345],
    [590, 1153],
    [1130, 1180]],
   'lectura': 'la Ciudad Autónoma de\n\na veintidós de febrero de dos\n\nargentina,\n\nescribano autorizante comparecen : Dora\n\nna, nacida e1 10 de marzo de 1966, casada\n\n\'on Raul Alberto Lescano». comerciante,\n\nentidad 17.636.488, CO ER 27-17636488-\n\nnacida el 6 de marzo d\n\nANO, argentina,\n\nte, Documento Nacional de Identidad 41.048\n\n1026-9», ambas con «Aomicilio real en Pic\n\npersonas que identifico de acuerdo\n\nya relacionada que en copia autentica:\n\nINTERVIENEN por si y manifiestan ser soci\n\n-iedad denominada "* CONFECOM s.R.b.”,. <'}},
 'text': 'O DE sociedad DE RESPONSABILIDAD LIMITADA. “CONFECOM S. 12) ROA, argentina casada en primeras nupcias con Raul Alberto LESCANO, nacida el 10 de marzo de 1966, comerciante, titular del documento nacional de identidad numero 17.636.488, C.U.I.T. 27-17636488-8, y Yamila Belen LESCANO, argentina soltera, nacida el 6 de marzo de 1998, comerciante, titular del documento nacional de identidad numero 41.048.026, C.U.I.L. 27-41048026-9, ambos domiciliado en Pico 4785, ciudad autonoma de buenos Aires; resuelven dejar constituida una sociedad de responsabilidad limitada que se regira por la Ley numero 19.550/22.903 y el siguiente estatuto primera La sociedad se denomina "CONFECOM S.R.L."” y tiene su domicilio legal en jurisdiccion de la ciudad autonoma de buenos Aires, pudiendo establecer agencias o sucursales en cualquier lugar del pais o del extranjero.- segunda Su duracion es de 99 años contados a partir de la inscripcion en el registro Publico de Comercio. - TERCERA La sociedad tiene por objeto realizar por cuenta propia o de terceros, en forma independiente o asociadas a terceros, dentro o fuera de la republica argentino a las siguientes actividades Compraventa, importacion, exportacion, comercializacion, representacion, fabricacion, refaccion, composicion, confeccion, deposito, transporte, despacho e industrializacion de todo tipo de ropa, indumentaria, calzado y sus derivados, botoneria, merceria, articulos textiles, materias primas, productos y subproductos destinados a la industria del vestido, y demas prendas y accesorios inherentes al ramo. Para el cumplimiento del objeto social, la sociedad tendra plena capacidad juridica para adquirir derechos y contraer obligaciones y ejercer actos que no sean prohibidos por las leyes o este estatuto.- CUARTA El capital social se fija en la suma de pesos cincuenta mil ($50.000) dividido en 5.000 cuotas de valor nominal $ 10 cada en un 23 por ciento y el resto se integrara dentro de los plazos legales.- QUINTA La administracion y representacion legal estara a cargo de uno o mas gerentes, socios o no, en forma individual e indistinta, por el plazo de duracion de la sociedad En tal caracter tienen todas las facultades para realizar los actos y contrato tendientes al cumplimiento del objeto de la sociedad inclusive los previstos en los articulos 375, del Codigo Civil y Comercial, y 9 del Decreto ley 5.965/63.- Los gerentes garantizaran su gestion mediante la constitucion de una garantia del tipo, modalidades y de los montos no inferiores a los establecidos en las resoluciones vigentes de la autoridad administrativa de control y las que se dicten con posterioridad.- SEXTA Las resoluciones sociales se adoptaran en la forma dispuesta en los arts. 159, primera parte parrafo segundo de la ley 19550.- Rigen las mayorias previstas en el art. 160 de la ley 19.550.- y cada cuota da derecho a un voto. Toda comunicacion o citacion a los socios se sujetara a lo dispuesto en el art. 159 ultimo parrafo de la ley citada.- SEPTIMA Las cuotas son transmisibles rigiendo las disposiciones del art. 153 de la ley 19.550, dejando constancia que para la venta a extraños a la sociedad se requerira la conformidad de la mayoria del capital, estableciendo a favor de los restantes socios un derecho de preferencia en la compra de las cuotas sociales que se vendan.- OCTAVA El ejercicio social cierra el 31 de Marzo de cada año, a cuya fecha se realizara el balance general que se pondra a disposiciones de los socios con no menos de 15 dias de anticipacion a su consideracion.- NOVENA De las utilidades liquidas y realizadas se destinaran a) El 5% al fondo de reserva legal, hasta alcanzar el 20% del capital social.- b)El importe que se establezca para retribucion de los gerentes y Cc) El remanente previa deduccion de cualquier otra reserva que los socios dispusieran constituir se distribuira entre los mismos en proporcion al capital integrado.- DECIMA Disuelta la sociedad por cualquiera de ¡as causales previstas en el articulo 94 de la ley 19.550.-, la liquidacion sera pracla ciudad autonoma de a veintidos de febrero de dos argentina escribano autorizante comparecen Dora na, nacida e1 10 de marzo de 1966, casada \'on Raul Alberto Lescano». comerciante, entidad 17.636.488, CO ER 27-17636488- nacida el 6 de marzo d ANO, argentina te, documento nacional de identidad 41.0481026-9 », ambas con «Aomicilio real en Pic personas que identifico de acuerdo ya relacionada que en copia autentica INTERVIENEN por si y manifiestan ser soci -iedad denominada "* CONFECOM s.R.b.”,. <',
 'entities': {'search': ['firmantes_nombre',
   'firmantes_dni',
   'socios_nombre',
   'razon_social',
   'tipicidad',
   'vigencia',
   'capital',
   'num_escritura',
   'fecha_contrato',
   'mandato_dir',
   'tipo_rep_legal',
   'facultades_firm',
   'aporte_socios',
   'fecha_cierre_ejercicio',
   'objeto_social',
   'cargo_firmantes',
   'legal_domicilio',
   'sede_domicilio',
   'firma_domicilio',
   'poderes_especiales',
   'reservas_legales',
   'garantias_directorio',
   'aumentos_capital',
   'firmante_domicilio',
   'firmante_familiar',
   'fecha_nacimiento',
   'fecha_final_doc'],
  'tags': [{'tag': 'firmante_familiar',
    'start': 106,
    'end': 126,
    'text': 'Raul Alberto LESCANO',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'fecha_nacimiento',
    'start': 138,
    'end': 157,
    'text': '10 de marzo de 1966',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'firmantes_dni',
    'start': 223,
    'end': 233,
    'text': '17.636.488',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'firmantes_nombre',
    'start': 261,
    'end': 281,
    'text': 'Yamila Belen LESCANO',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'fecha_nacimiento',
    'start': 312,
    'end': 330,
    'text': '6 de marzo de 1998',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 1},
   {'tag': 'firmantes_dni',
    'start': 396,
    'end': 406,
    'text': '41.048.026',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'firmante_domicilio',
    'start': 438,
    'end': 496,
    'text': 'domiciliado en Pico 4785, ciudad autonoma de buenos Aires;',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 1},
   {'tag': 'tipicidad',
    'start': 529,
    'end': 565,
    'text': 'sociedad de responsabilidad limitada',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'razon_social',
    'start': 669,
    'end': 685,
    'text': 'CONFECOM S.R.L."',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'legal_domicilio',
    'start': 736,
    'end': 767,
    'text': 'ciudad autonoma de buenos Aires',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'vigencia',
    'start': 884,
    'end': 886,
    'text': '99',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'objeto_social',
    'start': 973,
    'end': 1766,
    'text': ' La sociedad tiene por objeto realizar por cuenta propia o de terceros, en forma independiente o asociadas a terceros, dentro o fuera de la republica argentino a las siguientes actividades Compraventa, importacion, exportacion, comercializacion, representacion, fabricacion, refaccion, composicion, confeccion, deposito, transporte, despacho e industrializacion de todo tipo de ropa, indumentaria, calzado y sus derivados, botoneria, merceria, articulos textiles, materias primas, productos y subproductos destinados a la industria del vestido, y demas prendas y accesorios inherentes al ramo. Para el cumplimiento del objeto social, la sociedad tendra plena capacidad juridica para adquirir derechos y contraer obligaciones y ejercer actos que no sean prohibidos por las leyes o este estatuto',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'capital',
    'start': 1822,
    'end': 1845,
    'text': 'cincuenta mil ($50.000)',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'tipo_rep_legal',
    'start': 2081,
    'end': 2104,
    'text': 'individual e indistinta',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'mandato_dir',
    'start': 2113,
    'end': 2145,
    'text': 'plazo de duracion de la sociedad',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'facultades_firm',
    'start': 2146,
    'end': 2382,
    'text': 'En tal caracter tienen todas las facultades para realizar los actos y contrato tendientes al cumplimiento del objeto de la sociedad inclusive los previstos en los articulos 375, del Codigo Civil y Comercial, y 9 del Decreto ley 5.965/63',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'garantias_directorio',
    'start': 2384,
    'end': 2642,
    'text': ' Los gerentes garantizaran su gestion mediante la constitucion de una garantia del tipo, modalidades y de los montos no inferiores a los establecidos en las resoluciones vigentes de la autoridad administrativa de control y las que se dicten con posterioridad',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'fecha_cierre_ejercicio',
    'start': 3367,
    'end': 3378,
    'text': '31 de Marzo',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0},
   {'tag': 'reservas_legales',
    'start': 3549,
    'end': 3912,
    'text': 'De las utilidades liquidas y realizadas se destinaran a) El 5% al fondo de reserva legal, hasta alcanzar el 20% del capital social.- b)El importe que se establezca para retribucion de los gerentes y Cc) El remanente previa deduccion de cualquier otra reserva que los socios dispusieran constituir se distribuira entre los mismos en proporcion al capital integrado',
    'value': '',
    'extra1': '',
    'extra2': '',
    'index': 0}]}}